name: Compile Bun Code
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [release]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build